### PR TITLE
upgrade version upper boundary of slim to v4.0.1

### PR DESCRIPTION
**Pull request by Jakenberg**
This is in regards to issue #1284.

### CODE REVIEW

**Comment by presidentbeef** [comment]
@Jakenberg Thanks for looking into this.

Can you add an example of the new syntax to a Slim template in https://github.com/presidentbeef/brakeman/tree/master/test/apps/rails5.2 for testing? Thanks!

**Comment by Jakenberg** [comment]
No problem. Added what I think you mean. Let me know if it should be different 👍

**Comment by presidentbeef** [comment]
Okay, asking you to add the test was a mistake since Ruby 1.9.3 is not supported by Slim 4.0 :(

Do you mind backing that change out and then I'll merge? Thanks again!

**Comment by Jakenberg** [comment]
Bummer :( Updated

**Comment by presidentbeef** [comment]
Thanks!

**Pull request merged**
