### PR TITLE
Bump ruby_parser to support Ruby 3.1

### PR DESCRIPTION
**Pull request by sqbell**
Probably more is needed but that was enough for our suite to pass.

### CODE REVIEW

**Comment by presidentbeef** [comment]
Awesome, I didn't see that release!

Adding 3.1 to the test matrix doesn't really do anything to test RubyParser with 3.1 syntax.

Can you add a bit of code somewhere in https://github.com/presidentbeef/brakeman/tree/main/test/apps/rails7 using some new 3.1 syntax?

**Comment by sqbell** [comment]
@presidentbeef Sample code added in 0d2a488, but it does not fail `rake` with the old `ruby_parser`. Checking what's going on.

**Comment by presidentbeef** [comment]
Awesome, thanks!

**Comment by willfish** [comment]
This is great! Any chance of cutting a release for this?

**Comment by presidentbeef** [comment]
@willfish yes, this is released with Brakeman 5.2.2.

**Pull request merged**
