### PR TITLE
Fix version_between? method

### PR DESCRIPTION
**Pull request by aglushkov**
Fixes https://github.com/presidentbeef/brakeman/issues/1404

### CODE REVIEW

**Comment by presidentbeef** [comment]
Thanks @aglushkov, this seems to be heading in the right direction! If you rebase onto master it should resolve two of the test failures.

The `test_number_of_warnings` failure is concerning, though. It suggests Brakeman is not correctly detecting the version of Rails being used.

**Comment by aglushkov** [comment]
@presidentbeef thanks for help with broken tests, everything is fixed

Updated protect_from_forgery min version from 5.2.0 to 5.2.0.beta1 to fix `test_number_of_warnings`. 
Rails changelogs shows it should be 5.2.0.beta1 https://github.com/rails/rails/blob/v5.2.0.beta2/actionpack/CHANGELOG.md

**Comment by presidentbeef** [comment]
Thanks! :rocket:

**Comment by cabello** [comment]
@presidentbeef I understand you are on vacation, so please enjoy it, if possible would you mind sharing an ETA for this version to hit Rubygems? 

The reason I ask is that I have a few dozen repos using it and if it goes to Rubygems the new version will be automatically updated, otherwise I have to put PRs for each repo pointing it to `master` branch.

Thanks for making such useful software, I appreciate it 🙏

**Comment by presidentbeef** [comment]
I will attempt to get a release out this week. It is overdue.

**Comment by presidentbeef** [comment]
@cabello - I pushed out a release: https://brakemanscanner.org/blog/2019/10/14/brakeman-4-dot-7-released

**Comment by cabello** [comment]
Thank you very much 🙇

**Pull request merged**
