### PR TITLE
check for the latest version with new option

### PR DESCRIPTION
**Pull request by tamgrosser**
wip @grosser

### CODE REVIEW

**Comment by presidentbeef** [comment]
Hi,

Thank you for putting this together. I think it would be better to use the `Gem` interface though, in case of API changes: http://www.rubydoc.info/stdlib/rubygems/Gem.latest_version_for

**Comment by grosser** [comment]
update!
a few observations:
 - tests are in a weird folder and do not end in _test.rb ... makes finding/working with them hard
 - tests cannot run on their own ... makes testing in isolation hard
 - there are no tests for commandline option handling in bin/brakeman

**Comment by presidentbeef** [comment]
Thanks, this looks good.

* The tests are in `test/tests/` and used to also have `test_...` in the name and I couldn't take the triple redundancy.
* You can run individual tests with `ruby test/test.rb --name ...`
* Yes, this is true and has come up before and someone said they'd contribute testing for it...

**Comment by grosser** [comment]
Anything needed for merge ?

**Comment by presidentbeef** [comment]
Seems to work fine.

A couple minor things:

* This should have a specific exit code like the `-z`
* The option should be up around `-z` not in the scanning options section

**Comment by grosser** [comment]
updated, looks better ?

**Comment by presidentbeef** [comment]
Thanks!

**Pull request merged**
