### PR TITLE
Relax dependency on highline

### PR DESCRIPTION
**Pull request by johnnyshields**
It conflicts with Capistrano and others.

### CODE REVIEW

**Comment by presidentbeef** [comment]
What are "and others"? Capistrano doesn't depend directly on highline. If you have the output from bundler, that would be useful. 

Highline 1.7.0 dropped Ruby 1.8 support but I'm not ready to give up on it. If you really need the latest highline, you can use brakeman-min.

**Comment by johnnyshields** [comment]
So, it looks like I can safely downgrade highline, but why not relax the dependency on highline within Brakeman itself and just add a note "If you are using Ruby 1.8, please set `highline <= 1.6`". This way users can choose.

(For CI purposes you can setup Travis so the Ruby 1.8 build uses a 1.8-specific gemfile which has highline 1.6)

On a separate note, anyone who is serious enough about software security to use Brakeman should stop using Ruby 1.8!

**Comment by presidentbeef** [comment]
This still sounds like a Bundler problem to me if you were able to resolve the dependency manually.

I'll think about options for the next major release.

**Comment by presidentbeef** [comment]
This will updated in the next release. Thanks!

**Comment by johnnyshields** [comment]
@presidentbeef thanks for helping out

**Pull request closed without merging**
