### PR TITLE
Added Common Weakness Enumeration (CWE) IDs to reported vulnerabilities

### LINKED ISSUE #1636: CWE information
Hello Team,

The internal vulnerability identifiers/issues used by brakeman cannot be mapped to commonly used vulnerability metrics such as CWE. Some environments may require CWEs to be used as a standard for categorizing vulnerabilities. In addition, CWE mappings are very useful to consolidate vulnerability reports produced by different tools.

Describe the solution you'd like
Every vulnerability should get assigned a CWE identifier.

### PR DESCRIPTION
**Pull request by saghaulor**
- Closes #1636 
 - The methodology used to assign CWEs to a vulnerability is as follows:
    If the vulnerability has a CVE, and that CVE has CWEs associated with it,
    then those CWEs are used.
    If a vulnerability has a CVE, but does not have CWEs associated with it,
    then I chose the best applicable CWE(s) according to my understanding of the vulnerability and the CWE.
    If the vulnerability does not have a CVE,
    then I chose the best applicable CWE(s) according to my understanding of the vulnerability and the CWE.
 - Given that the NVD site indicates that in some rare cases a vulnerability can have multiple CWEs, and
    that some of the reported vulnerabilities with a CVE do in fact have multiple CWEs, an array was used as the
    data structure so as to allow reporting multiple CWEs.
 - Added a test helper to ensure that warnings contain a CWE with consistent format

 TODOs:
 - Ideally the CWEs include links to the respective CWE on cwe.mitre.org, however, I am unclear of where exactly this should 
   happen.
 - Add tests for report formats.

### CODE REVIEW

**Comment by saghaulor** [comment]
@presidentbeef I wanted to open this early so that you could take a look and provide feedback on the approach (to what extent that you can, as I am aware that you worked on this same feature in a proprietary context so you are limited in what you can contribute or else you may commit a crime or breach a contract). Specifically, I'm not sure how the reporting code works. I got it working mostly by trial and error.

I was thinking that each CWE should be a link to the cwe.mitre.org page, however, I'm not sure if that's appropriate for all report formats. And if it is not, where would I work in such changes for the different report formats? Also, does it make sense to add a test to warnings to ensure that they have an associated CWE?

Any feedback would be appreciated.

**Comment by presidentbeef** [comment]
Hey @saghaulor ! Thank you for working on this. Array for CWEs sounds good to me.

> I was thinking that each CWE should be a link to the cwe.mitre.org page, however, I'm not sure if that's appropriate for all report formats.

I think this is more of a presentation thing. I suppose it would make sense in HTML and Markdown... maybe others that are going to be viewed in an HTML context?

>  where would I work in such changes for the different report formats?

https://github.com/presidentbeef/brakeman/tree/main/lib/brakeman/report/

> Also, does it make sense to add a test to warnings to ensure that they have an associated CWE?

Yes, absolutely. I'd add it to the helper in [test/to_test.rb](https://github.com/presidentbeef/brakeman/blob/main/test/to_test.rb) 

And you can add a test like [test_every_warning_has_a_file](https://github.com/presidentbeef/brakeman/blob/main/test/test.rb#L117) to at least check the CWEs exist.

**Comment by presidentbeef** [comment]
> Specifically, I'm not sure how the reporting code works. I got it working mostly by trial and error.

You'll definitely want to add it [here](https://github.com/presidentbeef/brakeman/blob/main/lib/brakeman/warning.rb#L286)

You started with the oldest and weirdest report format, so understandable that it was confusing.

**Comment by presidentbeef** [comment]
I'm also happy to work on the reporting side once the data is there.

**Comment by saghaulor** [comment]
Update: I'm still working on this. My time is quite limited right now. I just wanted you/the community to know that I haven't abandoned it.

**Comment by saghaulor** [comment]
@presidentbeef there seem to be a couple tests related to CWEs that are failing that I'm having trouble tracking down. It would be good if we could somehow include more context to better locate failures.

Also, there seem to be a few unrelated test failures. 

Are you able to help me pinpoint where the CWE failures are originating from and to figure out the seemingly unrelated test failures? Thank you again for your time.

**Comment by saghaulor** [comment]
I think I'm going to leave out the mitre links from this PR. We can add them in another PR. What's important is that all warnings now have a CWE.

**Comment by saghaulor-coupa** [comment]
@presidentbeef is there anything else that I need to do to get this merged?

**Comment by presidentbeef** [comment]
If you can get me a few more hours in the day, that would be appreciated 😆 

No requested changes right now.

**Comment by presidentbeef** [comment]
#yolo

**Pull request merged**
