### PR TITLE
Allow `symbolize_keys` to be called on params

### LINKED ISSUE #1206: False positive SQL injection when using `symbolize_keys` on `ActionController::Parameters.to_hash`
### Background

Brakeman version: 4.3.0
Rails version: 5.1.6
Ruby version: 2.5.1

#### False Positive

First of all, thanks so much for releasing 4.3.0! It's been awesome seeing all of the improvements.

It looks like I simplified our code a bit too much when creating the reproducible case for #1180. While we were calling `to_hash` on the `ActionController::Parameters` object, we also call `symbolize_keys` on _that_ because [Sequel](http://sequel.jeremyevans.net) requires keys to be symbols. Here's an example:

```ruby
def index
  # Using Sequel, though don't think it matters.
  people = Person.where(index_params).all
  render json: people
end

def index_params
  # The `to_hash` is necessary for Sequel's `where` method.
  params.permit(:name).to_hash.symbolize_keys
end
```

I believe this is a false positive, as `symbolize_keys` doesn't really change the semantics of the hash. The Brakeman error disappears if I remove the `.symbolize_keys`.

**EDIT:** I've extracted part of this issue into a new issue: #1216.

### PR DESCRIPTION
**Pull request by JacobEvelyn**
Fixes #1206

### CODE REVIEW

**Comment by presidentbeef** [comment]
:cool: Thanks!

**Comment by JacobEvelyn** [comment]
Thanks for the quick merging of these two PRs, @presidentbeef! Selfishly, it would help us a lot if you could release a new gem version soon, but I'll let you determine when it makes the most sense for you. 😄

**Comment by presidentbeef** [comment]
A release takes about a full day of work, so hard to say. Maybe very soon, schedule permitting.

That being said, master is pretty much always stable.

**Comment by JacobEvelyn** [comment]
Gotcha, thanks for the info!

**Pull request merged**
