### PR TITLE
[update] haml dependency

### PR DESCRIPTION
**Pull request by joshRpowell**
see: https://github.com/haml/haml/releases/tag/v5.0.0

### CODE REVIEW

**Comment by presidentbeef** [comment]
Brakeman depends on the internal compiler output of Haml/Slim/ERB, so updates like this are problematic.

Brakeman also bundles all dependencies. So unless there is a Haml 5.0 feature you are using that doesn't work in Haml 4.0 or you are using `brakeman-lib`, there is no need to upgrade immediately.

**Comment by joshRpowell** [comment]
@presidentbeef thanks for breakman and the quick response.
Nothing urgent in 5.0 that we can't workaround on our end.  
I'll close the PR and leave #1044 open for reference. 
Thank again!

**Comment by presidentbeef** [comment]
What issues are you having to work around? Haml 5.0 features?

**Comment by swalberg** [comment]
I run Brakeman in CI with a rake task

``` 
 require 'brakeman'
 desc 'Run brakeman'
     task :brakeman do
        Brakeman.run app_path: '.', output_files: ['brakeman-output.tabs']
     end
```

After updating HAML from 4.0.7 to 5.0.0, Brakeman has been failing with:

```Error when processing admin/application/_navbar: Error when processing admin/application/_navbar: Error when processing admin/application/_navbar: Error when processing admin/application/_navbar: Error when processing admin/application/_navbar: Unrecognized action on _hamlout: fix_textareas!
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/brakeman/processors/haml_template_processor.rb:61:in `process_call'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/brakeman/processors/template_processor.rb:25:in `process'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/brakeman/processors/haml_template_processor.rb:14:in `process_call'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/brakeman/processors/template_processor.rb:25:in `process'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/brakeman/processors/base_processor.rb:150:in `block in process_arglist'
(eval):3:in `map!'
(eval):3:in `map!'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/brakeman/processors/base_processor.rb:149:in `process_arglist'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/brakeman/processors/template_processor.rb:25:in `process'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/brakeman/processors/haml_template_processor.rb:100:in `process_call'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/brakeman/processors/template_processor.rb:25:in `process'
/Users/sean/.gem/ruby/2.3.1/gems/brakeman-3.6.0/lib/brakeman/processors/haml_template_processor.rb:118:in `block in process_block'
(eval):3:in `map!'
(eval):3:in `map!'
...
```

Brakeman 3.6.1 and 3.6.0 and HAML 5.0.0, works in 4.0.7.

You mentioned above that this should work -- since I'm `requiring` the gem inside my application and I'm using bundler, is there a better way to do this?

Thanks!

**Pull request closed without merging**
