### PR TITLE
Fix error for endless method

### PR DESCRIPTION
**Pull request by mitsuru**

### CODE REVIEW

**Comment by presidentbeef** [comment]
Thanks @mitsuru!

I think this is a ruby_parser bug...

```ruby
3.0.0 :003 > RubyParser.new.parse 'def x = y'
 => s(:defn, :x, nil, s(:call, nil, :y)) 
3.0.0 :004 > RubyParser.new.parse 'def x; y; end'
 => s(:defn, :x, s(:args), s(:call, nil, :y))
```

Those should not be different.

**Comment by zenspider** [comment]
Agreed... Release with fix coming soon

**Comment by zenspider** [comment]
released

**Comment by presidentbeef** [comment]
Thanks @zenspider !

@mitsuru you can use this fix today by using the `brakeman-lib` gem and combining with the latest `ruby_parser`.

**Pull request closed without merging**
