### PR TITLE
Update Code Climate to use API instead of CLI

### PR DESCRIPTION
**Pull request by presidentbeef**
Avoid trying to build up a command line invocation.

### CODE REVIEW

**Comment by maxjacobson** [comment]
Ah, this approach seems really solid! Do you want me to try building and testing the engine on a repo with some strangely named files tomorrow?

**Comment by presidentbeef** [comment]
@maxjacobson Yes, please give it a spin.

**Comment by maxjacobson** [comment]
OK! I can confirm that this does neatly work around the issue in the case where there is a file in the root of the project called, e.g. `foo,`. No more error, and it does include the file.

One other thing I'm observing at this point is that if I rename an existing file, e.g. `app/views/codes/show.html.slim` -> `app/views/codes/show,.html.slim`, then it just silently skips that file without raising an error, even on this branch. I confirmed that it is present in the [`template_paths`](https://github.com/presidentbeef/brakeman/blob/142106b015f414e21d05cb2b1c011ca95a53ab6f/lib/brakeman/app_tree.rb#L103-L105), so I'm not sure where it's being filtered out

**Comment by presidentbeef** [comment]
@maxjacobson does the file name with a comma get skipped even without the `include_paths` option?

**Comment by maxjacobson** [comment]
@presidentbeef Correct. Commented out those lines and the behavior is the same. The paths aren't passed, and the options (when parsed) look like this:

```
{:quiet=>true,:output_format=>:to_codeclimate, :output_files=>["/dev/stdout"]}
```

And it skips the file called `app/views/codes/show,.html.slim`.

This is the same on master as this branch. So, to be clear, this branch looks good to me 👍 but it seems like the AppTree logic might skip some (strangely named) files fwiw

**Comment by presidentbeef** [comment]
Yeah, that's what I suspected. I think I'm okay with that...

**Comment by maxjacobson** [comment]
👍 same

**Pull request merged**
