### PR TITLE
Use SafeYAML to load configuration files

### PR DESCRIPTION
**Pull request by presidentbeef**

### CODE REVIEW

**Comment by bf4** [comment]
If you don't own your configuration files you're in trouble safeyaml can't help you with :)  (Also, Ruby 2.0+ Has `YAML.safe_load`)

**Comment by presidentbeef** [comment]
This is mostly for people providing Brakeman as a Service.

**Comment by bf4** [comment]
So maybe just check if YAML responds to 'safe_load'?

B mobile phone

**Comment by presidentbeef** [comment]
To what end? That doesn't help people using Ruby < 2.0. Not everyone is running Brakeman on trusted code. It is unexpected behavior for a static analysis tool to execute any of the code being scanned and I greatly prefer to avoid it.

**Pull request merged**
