### PR TITLE
Add support for Code Climate debug option

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
cc @mrb

### CODE REVIEW

**Comment by presidentbeef** [comment]
This won't affect the Code Climate report. Will you be capturing STDERR?

**Comment by presidentbeef** [comment]
@ABaldwinHunter any comment? Just trying to understand the use case.

**Comment by ABaldwinHunter** [comment]
Hey @presidentbeef! apologies missed your earlier comment. Thanks for following up!

We capture and output stderr in two cases:

- [in the CLI](https://github.com/codeclimate/codeclimate#environment-variables) when `CODECLIMATE_DEBUG=1` is passed
- on codeclimate.com the stderr gets output occasionally in engine build step, like the duplication engine [here](https://codeclimate.com/github/presidentbeef/brakeman/builds/71)

Typically we wouldn't run engines in that mode, but occasionally the introspection can be useful when an analysis errors.

Let me know what you think :)

**Comment by presidentbeef** [comment]
Makes sense, just wanted to be sure.

I would recommend adding `--no-progress` to avoid control codes in the output. It's a little easier to read that way.

**Comment by presidentbeef** [comment]
Looks like the build failed because `terminal-table` 1.7.2 accidentally broke Ruby 1.9.3 compatibility (https://github.com/tj/terminal-table/issues/79), so no worries.

**Comment by ABaldwinHunter** [comment]
Cool, thanks!

**Pull request merged**
