### PR TITLE
Added direct line to file

### PR DESCRIPTION
**Pull request by dukaev**
With direct line it will be faster to open the file

For example https://www.dropbox.com/s/caxgsfhw5ftpxp4/sublime.mp4?dl=0

### CODE REVIEW

**Comment by dukaev** [comment]
@presidentbeef hello!
What do you think about it?

**Comment by presidentbeef** [comment]
Hi @dukaev - thanks for opening this PR.

The line number is already included in the output, though, so I think it would be weird to add it to the file name:
Screen Shot 2019-09-23 at 11 20 27 AM

**Comment by dukaev** [comment]
I agree. But it would make it easier to navigate the code

**Comment by dukaev** [comment]
@presidentbeef and what about now https://github.com/presidentbeef/brakeman/pull/1400/commits/21f05f72fdf75fea840dc9102d9fd47a8e9363b9 ? 😂

**Pull request closed without merging**
