### PR TITLE
Only run scans when test runs

### PR DESCRIPTION
**Pull request by presidentbeef**
Also, since scans are no longer run upfront, make them quiet so they don't mess up the test output.

/cc @ichthala

### CODE REVIEW

**Comment by ichthala** [comment]
It looks like the rake task won't run these tests anymore, since run_scan will no longer be called when the files are required. Is there an alternate way to run them that I'm not seeing?

**Comment by presidentbeef** [comment]
Hm, running with rake seems to work fine for me and Travis?

Alternatively you can run `ruby test/test.rb` (which is exactly what the rake task does).

**Comment by ichthala** [comment]
I see what I was missing — I didn't realize that the tests sent the `report` message themselves, so I thought that `run_scan` would only be called when the files were required in test.rb.

Also, it looks like the tests for scans with the :only_files option weren't changed over to the new pattern. Is that intentional?

**Comment by presidentbeef** [comment]
Nope, I missed that one, thanks! Updated.

**Pull request merged**
