### PR TITLE
Adds obsolete ignore filter identification functionality

### PR DESCRIPTION
**Pull request by jcheatham**
@presidentbeef - re https://github.com/presidentbeef/brakeman/issues/893

wasn't too sure about the tests... wanted to spike on this to assess our own situation,  figured it might help give you some inspiration, feel free to disregard, tear it apart, whateva :)

Outputs something like:

```
+SUMMARY+

+-------------------+-------+
| Scanned/Reported  | Total |
+-------------------+-------+
| Controllers       | 123   |
| Models            | 321   |
| Templates         | 234   |
| Errors            | 1     |
| Security Warnings | 0 (0) |
| Ignored Warnings  | 128   |
+-------------------+-------+


+Obsolete Ignore Entries+
+------------------------------------------------------------------+
| fingerprint                                                      |
+------------------------------------------------------------------+
| 26e7d2ae32aad50f0daaff757412b46619b99345533eb156a175c0b3734713d0 |
| 3d7db177b95dd7ab42bb830fd340638a26950f6cd98677735cc0eb3793ad3ecb |
| b2d8456d8bfe5d3c5e945ce92a8eb474af5f20e62af48bd1fd2468aeca8b66f2 |
| c9af0ab4e9fa302ac14cc32b4ba8b63a75d5c6559ecca9cfd2d081c87086d816 |
| ed8407625864e4fce50f5754b1322cf1d873da8f7cd79dfc0b9dd6e3f985b389 |
| ff2b76e22c9fd2bc3930f9a935124b9ed9f6ea710bbb5bc7c51505d70ca0f2d5 |
+------------------------------------------------------------------+

+Errors+
etc.
```

### CODE REVIEW

**Comment by grosser** [comment]
maybe `--fail-on-unused` while you are at it ?

**Comment by presidentbeef** [comment]
I'm not disregarding :)

I don't think this needs to be an option - it can be default behavior. It should also be added to the JSON report.

The "ignore" code is not super-well-tested, but this can be tested by grepping the text output ([see here](https://github.com/presidentbeef/brakeman/blob/master/test/tests/report_generation.rb#L57) for examples) and then also checking the JSON report once that's added ([see here](https://github.com/presidentbeef/brakeman/blob/master/test/tests/json_output.rb)).

**Comment by jcheatham** [comment]
No worries about "not disregarding", I understand how that goes very well :)

Made the updates you suggested: removed the option, added it to the JSON report, added/updated some tests.

**Comment by presidentbeef** [comment]
Thanks!

**Pull request merged**
