### PR TITLE
Skip branches with `Rails.env.test?'

### LINKED ISSUE #862: ignore code inside of 'if Rails.env.test?'
we have a few hacks here and there that bypass authentication / add catch-all routes to make tests easier to write ... would be nice if those would not get caught as errors

is that possible / would that make sense ?

@presidentbeef

### PR DESCRIPTION
**Pull request by presidentbeef**
closes #862 

@grosser can you test and see if this does what you wanted?

### CODE REVIEW

**Comment by grosser** [comment]
tried adding a match all route as a test and it was a warning:

```
# config/routes.rb
  if Rails.env.test?
    match '/:controller/:action'
  end
```

```
High ... routes.rb near line 124 |
```

**Comment by presidentbeef** [comment]
Okay, thanks. The specific test case is helpful.

**Comment by presidentbeef** [comment]
Should work now.

**Comment by grosser** [comment]
confirmed working! :D

**Comment by presidentbeef** [comment]
Great, thank you for testing!

**Pull request merged**
